### ISSUE TITLE
bump version to 1.1.1 to enable localhost / external binding

### ISSUE THREAD

**Issue by barecool** [brapifra/vscode-phpserver#10]
@brapifra could you push the latest version(bump to 1.1.0) in this repo to the vscode extension marketplace

so we can have the external binding functionality 

i have manually copied the changes that exist on the master to my local extension folder and it works great. 

but it would be nice to have the latest changes in the market place..

**Comment by brapifra** [comment]
I am planning to update the project with your request and a code review in the following days. Apologies for the non-maintenance :(

**Comment by brapifra** [comment]
Version 2.0.0 out!
