### ISSUE TITLE
Xampp parameters (PHP not found)

### ISSUE THREAD

**Issue by JaimeSFC** [brapifra/vscode-phpserver#107]
Hi Brais! happy new year btw 🥳
I have same issue as other users: "PHP not found"
I have Xampp installed and running, set the proper path in the settings JSon
```
  "php.validate.executablePath": "C:\\xampp\\php\\php.exe",
  "phpserver.phpPath": "C:\\xampp\\php\\php.exe",
  "phpserver.phpConfigPath": "C:\\xampp\\php\\php.ini"
```
And also run `php --version` in the Terminal to ensure php is found and OK,
But, still, same error message when trying to Serve Project

I must be missing something to **configure from the XAMPP**, but I cannot find any resources.
Could you provide any hint?
Thanks in advance!

**Comment by AlexanderAdelAU** [comment]
Yes, I am having the same problem.  I have spent over 2 days trying to figure this out.  After trying just about everything, I think I am convinced that those variables are not being using and ignored.   I have also tried to set the environmental variables but that does not work either.   Probably best to uninstall it I think and deploy manually.
