### ISSUE TITLE
White page

### ISSUE THREAD

**Issue by ohdude** [brapifra/vscode-phpserver#11]
I get a white page if I run the server

**Comment by brapifra** [comment]
Please give me more details. What files do you have in your project?

**Comment by ohdude** [comment]
One of them was a codenighter application, and the other one was a normal php file. I installed lamp on my ubuntu desktop (apt install lamp-server^)

**Comment by brapifra** [comment]
Did you check the browser's inspector? And does the popup notification "Running server" show in the vscode editor?

**Comment by brapifra** [comment]
No answer
