### ISSUE TITLE
Custom Server IP

### ISSUE THREAD

**Issue by umairhm** [brapifra/vscode-phpserver#15]
I want to change the IP value from localhost to 127.0.0.1. I updated user settings like in the screenshot below:

<img width="1326" alt="screen shot 2017-09-28 at 9 24 02 pm" src="https://user-images.githubusercontent.com/6948878/30978305-9eeaef88-a493-11e7-978c-9d3fb1e60750.png">

Please tell if this is fine or not because as soon as I make this change, I can't start the server. It starts and immediately stops automatically.

**Comment by brapifra** [comment]
Your settings are correct. I have updated the extension (v2.1.1) in order to show an error message that may help you to detect the problem (Perhaps 127.0.0.1 is already in use)
