### ISSUE TITLE
Why does it always show this?

### ISSUE THREAD

**Issue by dazhilang018900** [brapifra/vscode-phpserver#16]
When I click the Server Project with Php Server,   the Browser Show me this 

404 Not Found
The requested resource / was not found on this server.

this is my  PHP DEBUG 's  launch.json
{
            "name": "Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9000
}

this is my   setting.json
      "phpserver.browser":"edge",
      "phpserver.port":3000

BUT i can use ApacheServer normally , so ,i wanna to know if there is any mistake with my setting.

THANKs!!!

**Comment by brapifra** [comment]
According to your comment, the PHP server is up & running but it can't find the resource. The solution may be to specify the path to the resource you want (http://localhost:3000/src/index.php, for example)

**Comment by dazhilang018900** [comment]
thanks for your reply, but how to set my phpserver's path to the specified path

**Comment by brapifra** [comment]
With the `phpserver.relativePath` option

**Comment by dazhilang018900** [comment]
THANKS!!!    now ,i cant debug the index.php file,and the browser can display content normally, 
B U T, the output windows of PHP Server shows 
## " [Sun Nov 5 02:28:00 2017] [404]     /    - No such file or directory"  when i debugging , 
************THE LOCALs Variable like this *********
$funnPath: "C:\Users\dazhilang\Documents\VsCodeProj\phpweb./"
$path: "/"
$relativePath: "."

i have changed servel valuse for the $relativePath, But the value of $paht always  "/"   , So, I guess there is a problem with THE $path

**Comment by brapifra** [comment]
I am bit confused. Are you saying that the browser displays content properly but the output of the PHP server shows "[Sun Nov 5 02:28:00 2017] [404] / - No such file or directory ..." ?

**Comment by dazhilang018900** [comment]
![php](https://user-images.githubusercontent.com/16031711/32425561-f5405fac-c2ee-11e7-8d8e-e71d369e3c12.png)
ye，look at this pic

**Comment by brapifra** [comment]
What OS are you working on?

**Comment by prakash-patel** [comment]
What was the fix for this issue?

**Comment by brapifra** [comment]
I think there wasn't an issue at all. He probably had something misconfigured.
