### ISSUE TITLE
Can not stop server

### ISSUE THREAD

**Issue by RoraxHan** [brapifra/vscode-phpserver#17]
I installed this on mac.
I can start server by typing "Serve Project with PHP" or by clicking "Serve Project with PHP" in popup menu of vs code.
but I can't find "Stop PHP Server" from the Cmd+Shift+P or popup menu of editor.
How can I stop the server so that I can release the used port 3000?

**Comment by brapifra** [comment]
Hmm... That's weird. Can you upload a screenshot of the problem?

**Comment by RoraxHan** [comment]
![screen shot 2017-11-27 at 10 38 28 pm](https://user-images.githubusercontent.com/25556402/33305601-bde1a288-d3c3-11e7-9a23-62d0f5f898b3.png)

This is screenshot! As you can see I can see 'Serve Project with PHP' but can't see 'Stop Php Server'.
(In the windows 10, I can see both of 'Serve Project with PHP' and 'Stop PHP Server'.)

**Comment by brapifra** [comment]
I think that the other plugin that you have installed (Remote) is overwriting the option of the vscode-phpserver. Could you disable Remote and try again?

**Comment by RoraxHan** [comment]
I fixed this problem by removing "Remote VsCode" extensions.
that extensions makes the Override "Stop Server" feature of your extensions.
I hope this is helpful.
