### ISSUE TITLE
.htaccess not reading in

### ISSUE THREAD

**Issue by briantyszkaCM** [brapifra/vscode-phpserver#19]
I have a project that i am maintaining and it is trying to processing html files as php files.
using the following line in the .htaccess file.
AddType application/x-httpd-php .html

If i set it up through apache it will work fine but when running through phpserver it treats it as an html file.  Am i missing something?

**Comment by brapifra** [comment]
This extension uses the built-in php server, so I'm afraid that it doesn't use the .htaccess config at all :(

**Comment by mfuery** [comment]
Hello,
Can this issue be converted into a feature request? It would be very useful in many projects, since many CMS's and frameworks rely on requests redirecting to `/index.php`
Thanks

**Comment by ryouzue** [comment]
Same, if possible I'd love this to become a feature @brapifra 🙏🏼 `.htaccess` support

**Comment by palbcn** [comment]
+1

**Comment by IanWONeill** [comment]
+1

**Comment by florianmarical** [comment]
+1

**Comment by sitofelice** [comment]
<?php
for ($i = 0; $i < 100000; $i++) {
    echo "+1\n";
}
?>

**Comment by ccsimmons** [comment]
+1
