### ISSUE TITLE
No console output with 1.1.0

### ISSUE THREAD

**Issue by Venom-Code** [brapifra/vscode-phpserver#2]
Hello again :),

with the last update the console in vscode have no ouput and you cant stop the server with crtl + c (tested with 2 pc´s). 

But i like the open browser feature, thanks !

Greetings

**Comment by Venom-Code** [comment]
Oh i see the problem is known.  Im sorry

**Comment by brapifra** [comment]
Thanks again for the report, the ctrl+C feature it's not part of the issue I have disabled it on purpose, now you can stop the server with right click and selecting "Stop PHP Server" or  looking for the command with ctrl+shift+P. Nevertheless, the console in windows should have output, I'm working on it!
