### ISSUE TITLE
How to enable auto open in localhost?

### ISSUE THREAD

**Issue by Madebym** [brapifra/vscode-phpserver#21]
If I understood everything right, after serving the project with PHP server, the page should open automatically in a browser with this setting?

How should I do that? I am running VS Code on Mac OS High Sierra.

Thanks

**Comment by brapifra** [comment]
You have to configure the settings of VS Code:
```javascript
"phpserver.browser": "chrome" // Other valid options are "firefox" or "edge"
```

**Comment by Madebym** [comment]
@brapifra Thanks for the reply. I already did that, but nothing is happening.

Do I need to do something else besides that?

Just to recap. I have the browser set to Chrome(tried Firefox also), then I serve the project with PHP server. 
And nothing happens. I can only view the page by manually adding the URL to localhost:3000

**Comment by brapifra** [comment]
I didn't forget you!
I've checked it and you are right. It doesn't work properly.
I'm working on it.

**Comment by Madebym** [comment]
Haha, ok, no worries about that. Nice to hear you are already working on it.

**Comment by brapifra** [comment]
Fixed!
Let me know if you find another problem.
Thank you!

**Comment by Madebym** [comment]
Working like a charm !! Thanks
