### ISSUE TITLE
It opens Firefox instead of Firefox Nightly in macOS

### ISSUE THREAD

**Issue by gusbemacbe** [brapifra/vscode-phpserver#23]
Hola Brais,

The apps Firefox, Firefox Developer and Firefox Nightly have the same command name of 'firefox'. But it opens Firefox instead of Firefox Nightly.

I have already set `'firefox-nightly'` to `"phpserver.browser":`, instead of `firefox`, but it doesn't open Firefox Nightly because the true command name of this app is 'firefox'. 

¿Alguna solución?

¡Gracias!

**Comment by brapifra** [comment]
I'm afraid that due to the multi-platorm support I can't make the `"phpserver.browser"` option totally dynamic. It has to be chrome, firefox, edge or safari.
I could add this feature if you are extremely interested, but I think that just a few would find it useful.

**Comment by gusbemacbe** [comment]
You are right. 

I am really interested, but we are few, then you can discard this feature. 

I had to choose one of three Firefox editions. I chose Firefox Developer for macOS and Linux and set to `firefox`. In macOS, Firefox Developer opens normally, but in Linux, it doesn't open.
