### ISSUE TITLE
The requested resource / was not found on this server.

### ISSUE THREAD

**Issue by briantully** [brapifra/vscode-phpserver#24]
Installed the plugin and have left it with the default settings. However whenever I select "Serve project with PHP" it opens http://localhost:3000 and I see a page showing:

Not Found
The requested resource / was not found on this server.

Where is it getting the "/" value from? Shouldn't it open the file I have selected in the editor?

**Comment by brapifra** [comment]
The extension opens index.php by default.
You have to change the path `"/" ` for the file's one.

Similar issue: #22
