### ISSUE TITLE
Is there a shortcut to open the currently worked on file in the browser?

### ISSUE THREAD

**Issue by KietSam** [brapifra/vscode-phpserver#26]
Would like an "Open in browser" option which will open the current php file I'm working on in the current browser with the right url.

For example if I'm working on test.php I want to be able to right click, press "Open in browser", and have the webpage "localhost:3000/test.php" open up in my browser.

**Comment by brapifra** [comment]
The new 2.4.0 version comes with your request.
Let me know what do you think! Thank you!
