### ISSUE TITLE
Time server error

### ISSUE THREAD

**Issue by rafso** [brapifra/vscode-phpserver#27]
I'm having error related to time. applications such as wordpress have expired links error.
How can I configure server time?

thanks

**Comment by rafso** [comment]
The problem persists after adjusting timezone. When running projects like Wordpress or frameworks like yii2 or codigniter the application loses the session at all times or link expiration occurs.

**Comment by brapifra** [comment]
Have you tried to change the session path in php.ini?
`session.save_path="/tmp"`
