### ISSUE TITLE
Serve project not working well with project directories with spaces in name

### ISSUE THREAD

**Issue by KietSam** [brapifra/vscode-phpserver#31]
![asdfasdfdsaf](https://user-images.githubusercontent.com/5054996/39954879-c6ce105e-557b-11e8-85c2-009b2334a5f2.PNG)

When I serve the project I get this url:
http://localhost:3000/Creative

Which loads up this:
![gfdhfghfdghfgh](https://user-images.githubusercontent.com/5054996/39954886-fcd61cfa-557b-11e8-9dc4-37db357f7fc1.PNG)

I think it can be fixed by replacing spaces with %20
http://localhost:3000/Creative%20Projects/cp7/php/sidebar.php

**Comment by brapifra** [comment]
Done! Replacing spaces with %20 did work.
Thank you for the feedback!
