### ISSUE TITLE
Server not shutting down

### ISSUE THREAD

**Issue by vallieresc** [brapifra/vscode-phpserver#32]
Starts fine but will not shut down on right-click as indicated in your instructions. Only Stop PHP Server command works.

**Comment by BrianH2** [comment]
I had the same issue, but even the `Stop PHP Server` command didn't work. For anyone running into it, here's how to manually stop it on mac:

```
$ lsof -i :3000 # shows servers running on 3000 - note the PID number
$ kill -QUIT <PID_FROM_ABOVE>
```

More detail [here](https://stackoverflow.com/questions/3855127/find-and-kill-process-locking-port-3000-on-mac).

Great extension though - thanks for building it @brapifra 👍

**Comment by brapifra** [comment]
I think this problem could be caused by another installed extension (#17)
