### ISSUE TITLE
using phpserver with Debug

### ISSUE THREAD

**Issue by vblahoz** [brapifra/vscode-phpserver#37]
Is there a way to debug php files served by phpserver plugin?
I have XDebug installed and set, php-debug extension in VSCode seems to be working too (when php file is run from the command line the breakpoints work), however when php code is run by phpserver, breakpoints do not break.
Are there some settings I am missing?
Thanks

**Comment by brapifra** [comment]
Hi!

I think this [link](https://stackoverflow.com/questions/27496543/is-it-possible-to-use-xdebug-with-the-built-in-php-test-server) may be useful.
