### ISSUE TITLE
Error displaying code in extension

### ISSUE THREAD

**Issue by zazasco** [brapifra/vscode-phpserver#39]
its asking for php viewer and as well to change the server settings am Using Mamp server as my local host how to i change the default settings to the one in mamp.
![screenshot 16](https://user-images.githubusercontent.com/25632227/44626027-840e5180-a90d-11e8-9e5c-bfe2fe6ac581.png)

**Comment by brapifra** [comment]
Sorry, I can't understand the issue.

Can you explain it again?
