### ISSUE TITLE
It shows this error please help

### ISSUE THREAD

**Issue by AfnanSAhmed** [brapifra/vscode-phpserver#42]
Server error: Error: spawn php ENOENT at _errnoException (util.js:1024:11) at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19) at onErrorNT (internal/child_process.js:372:16) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by AfnanSAhmed** [comment]
When I start the php server I get one message 'Php server started' then the above error and then 'Php server ended'. similar...

**Comment by brapifra** [comment]
And did you try to set the ```phpserver.phpPath```?
I think this is a similar problem #43
