### ISSUE TITLE
PHP File Extension (Navigation Question)

### ISSUE THREAD

**Issue by rclafferty** [brapifra/vscode-phpserver#44]
I'm using your extension for work where we write a lot of internal links without the *.php extension (ex: "www.mysite.com/about" as opposed to "www.mysite.com/about.php"), which works on the live server. However, when hosting the site with your PHP server extension locally, it gives me the "file not found" page. Is there a setting that possibly supports this? Any help is greatly appreciated.

**Comment by brapifra** [comment]
Hmm... yeap, you are right. I'll take a look at the problem and I'll see what I can do.
Thanks!

**Comment by rclafferty** [comment]
Hi @brapifra. Is there any update on this issue yet? I tried the server script as you referenced, but did so very briefly and could not make it work yet. I will keep trying.

**Comment by brapifra** [comment]
Hi @rclafferty. I'm afraid that the custom router is the only possible solution :(
The script I've linked you should work, but let me know if you need anything else!

**Comment by manifestinteractive** [comment]
For others, like me who was looking for an actual example for a custom router for pretty URL's, this is what I came up with:

```php
<?php
$path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$relativePath = getenv('PHP_SERVER_RELATIVE_PATH');
$fullPath = $_SERVER["DOCUMENT_ROOT"] . $relativePath . $path;

if (!file_exists($fullPath) || is_dir($fullPath)) {
    file_put_contents("php://stderr", sprintf("[%s] %s", date("D M j H:i:s Y"), "[404] $path - No such file or directory "));
}
else {
    file_put_contents("php://stdout", sprintf("[%s] %s", date("D M j H:i:s Y"), "[200] $path"));
}

// Support for Pretty URL's
$ext = pathinfo($fullPath, PATHINFO_EXTENSION);
if ($ext === '' && substr($fullPath, -1) !== '/') {
  require($fullPath . '.php');
  return;
}

return false;
```
