### ISSUE TITLE
Server Stoped when opening Chrome Developer Tools

### ISSUE THREAD

**Issue by danihuge** [brapifra/vscode-phpserver#45]
Running on macOS, server stoped when I open the chrome developer tools for Inspecting CSS

**Comment by brapifra** [comment]
Could you please provide more details about the issue? @danihuge

**Comment by danihuge** [comment]
Hi @brapifra I tried to test and put some screenshots but I have upgraded my macbook to mojave and I am unable to start the server. 

In summary, these are my steps:
1.- Open Visual Studio Code
2.- Start Server
3.- Chrome is opened and the server is running
4.- Open Chrome Developer Tools for inspecting
5.- Server is stoped

I need to run: restart server to continue my work.

Regards,

**Comment by danihuge** [comment]
Hi @brapifra I rebooted my laptop and php server extension is working back again.

Screenshot attached

<img width="508" alt="captura de pantalla 2018-10-22 a las 19 01 48" src="https://user-images.githubusercontent.com/863891/47306684-6e778880-d62d-11e8-9f08-e32ab072285b.png">

**Comment by brapifra** [comment]
That was a really weird bug. I'm closing the issue now that it's fixed.
