### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by SarithRandir** [brapifra/vscode-phpserver#46]
When I try to start the PHP server i get this error : 

ERR_CONNECTION_REFUSED

**Comment by brapifra** [comment]
Are you sure you don't have another server running in the same port?

If that's not the case, could you please attach a screenshot? @SarithRandir

**Comment by Jackiin** [comment]
@brapifra If the port is occupied, is it possible to change the php server port?

**Comment by brapifra** [comment]
Yes @Jackiin 
You can change it in the VSCode settings: https://code.visualstudio.com/docs/getstarted/userinterface#_settings
