### ISSUE TITLE
Server still running after stopping

### ISSUE THREAD

**Issue by fupuchu** [brapifra/vscode-phpserver#48]
Heya, I ran into an issue where the server is still running even though I uninstalled it.

I reinstalled PHP Server to stop it from serving files and it's somehow still able to serve the pages.

**Comment by fupuchu** [comment]
Update: It doesn't kill the php process. I'm currently on macOS High Sierra 10.13.6

**Comment by brapifra** [comment]
Hey!

What do you mean by uninstalling it?
You should stop it by right-clicking on the vscode editor and selecting the `PHP Server: Stop`.
Have you tried that @fupuchu ?

Thanks

**Comment by profiluefter** [comment]
I have this issue and the command does not work
