### ISSUE TITLE
Can't connect to localhost:3000

### ISSUE THREAD

**Issue by shadyueh** [brapifra/vscode-phpserver#5]
Hi there. I tried start the server and it open my browser with localhost:3000 url but then I get a "The connection with localhost was refused. ERR_CONNECTION_REFUSED" on Chrome. Any suggestions what would it be? I'm using the default configs, just changed the "phpserver.browser" to "chrome"

**Comment by shadyueh** [comment]
Sorry for bother you. I realized my PHP wasn't in path. I usually set the path through the IDE I use. As a suggestion, you could add an optional configuration directive where we could set this. Best regards.

**Comment by brapifra** [comment]
No problem! I didn't understand what you mean. An optional configuration directive to what? Can you explain it better?

**Comment by shadyueh** [comment]
Yes. Where we could set the path to    our PHP home

Em 01/11/2016 18:20, "brapifra" <notifications@github.com> escreveu:
