### ISSUE TITLE
Great extension!  How does one use this in conjunction with PHP debugging?

### ISSUE THREAD

**Issue by TheMadStrater** [brapifra/vscode-phpserver#50]

**Comment by MarkSky** [comment]
I would like to know if it can be used with [PHP Debug](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug)?
Using it to running php web and debug?

**Comment by brapifra** [comment]
I don't see why not!

They are two completely separated extensions. @MarkSky @TheMadStrater

**Comment by MarkSky** [comment]
Ok, thank you.
But, both those two extension need to be setting?
