### ISSUE TITLE
Unknown: failed to open stream: No such file or directory in Unknown on line 0

### ISSUE THREAD

**Issue by NickBerkson** [brapifra/vscode-phpserver#51]
I am having a bit of trouble trying to get this extension to work. I'm New to coding so please excuse my ignorance. This was working about 4 or 5 months ago, but now I cant seem to figure it out. 

I have my paths set as  `""phpserver.phpPath": "C:/xampp/php/php.exe", ` and `"phpserver.relativePath": "C:/xampp/htdocs",`

I am not running xampp because I would like to replace it with this tool.

my terminal in vs code shows:
" "PHP Fatal error:  Unknown: Failed opening required 'c:\Users\********\.vscode\extensions\brapifra.phpserver-2.4.6\src\logger.php' (include_path='C:\xampp\php\PEAR') in Unknown on line 0" 

I don't have a logger.php file in my php folder, pear folder, htdocs, or in the src folder, do I need to create one? 

I don't know what a router is but googling suggests a windows startup script I don't think I have any or at least any I set up myself. (It would be nice if the documentation was a bit more clear on where one would typically find such a file or even how a start up script would effect a plugin. Then again I am new so pardon my ignorance.)
 
I'm using windows 10. I was at one point able to get the error in #42 and #43. I have since uninstalled xampp and vs code, and made sure no configuration files remained. I then reinstalled xampp, vs code and this extension. I do have a new firewall, however I have the server ports set to allow in this range and the firewall itself is on ask to connect and I haven't blocked anything that was obviously this. Any help would be greatly appreciated this tool makes learning so much less tedious! Thank you for your hard work!

**Comment by brapifra** [comment]
Hi @NickBerkson 

The problem is that you are using an absolute path in `phpserver.relativePath`.
You should be able to make it work by removing the `phpserver.relativePath` configuration and opening the `C:/xampp/htdocs` folder with VScode.

**Comment by NickBerkson** [comment]
Ah, thank you! 

I ended up deleting both settings, then I created a global environment variable for my PC to point at the php location. Seems to work. Hope I don't reinstall xampp and forget that's what I did at some point.

**Comment by NickBerkson** [comment]
And its broken again...

Fatal e
rror:  Unknown: Failed opening required 'c:\Users\*******\.vscode\extens
ions\brapifra.phpserver-2.4.6\src\logger.php' (include_path
='C:\xampp\php\pear') in Unknown on line 0

I've cleared all my settings so "phpserver.phpPath": "C:/xampp/php/php.exe" is the only setting in my .json file.

I've tried opening the folder with vscode (File -> Open Folder...) in htdocs and elsewhere 

I then tried adding :
 "php.validate.enable": true,
"php.executablePath": "C:\\xampp\\php\\php.exe",
"php.validate.executablePath": "C:\\xampp\\php\\php.exe",
I then removed those settings.  

 I also tried  :
"phpserver.phpPath": "C:\\xampp\\php\\php.exe",
"phpserver.phpPath": "C:/xampp/php/php.exe",

For my global windows path variable I tried :
C:\xampp\php;
then I tried changing it to :
C:\xampp\php\php.exe

I even edited my php.ini so it would say include_path = C:\xampp\php\pear

At this point I'm unsure what else to try. I feel dumb that I can't figure this out...

**Comment by blachawk** [comment]
i'm running into a simular situation.  The error I get in my case is 

`Fatal error: Unknown: Failed opening required 'c:\Users\...\.vscode\extensions\brapifra.phpserver-2.4.6\src\logger.php' (include_path='.;C:\php\pear') in Unknown on line 0`

Where can i go to remove `C:\php\pear`.  That's not even a real directory on my machine.  

Thanks!

**Comment by caiohamamura** [comment]
That's really strange, here in my machine the `logger.php` is located in `.vscode\extensions\brapifra.phpserver-3.0.2\src\server\logger.php` inside the `server` directory.

I found someone with the same problem, I'll check if I can help her to fix that. There's also this issue posted in superuser.stackexchange also https://superuser.com/questions/1646540/php-error-with-logger-php-unknown-failed-to-open-stream-no-such-file-or-di which he tells you to create the logger.php in the right location with the content:

```php
<?php
$path = parse_url($_SERVER["REQUEST_URI"], PHP_URL_PATH);
$relativePath = getenv('PHP_SERVER_RELATIVE_PATH');
$fullPath = $_SERVER["DOCUMENT_ROOT"] . $relativePath . $path;
if (!file_exists($fullPath) || is_dir($fullPath)) {
    file_put_contents("php://stderr", sprintf("[%s] %s", date("D M j H:i:s Y"), "[404] $path - No such file or directory "));
}
else {
    file_put_contents("php://stdout", sprintf("[%s] %s", date("D M j H:i:s Y"), "[200] $path"));
}
return false;
?>
```

**Comment by caiohamamura** [comment]
I've figured it out what was happening in this girl's machine, the Avast Antivirus was blocking `logger.php` and quarantined it, check if your antivirus isn't doing the same.

**Comment by Elyas-GO** [comment]
tnx caiohamamura 
restore server.php from avast antivirus quarantine work for me.
the error that i face when browsing 127.0.0.1:8000 is
Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

**Comment by Bimaajisatria** [comment]
gak iso bolo
