### ISSUE TITLE
Served file misses first 2 characters of filename

### ISSUE THREAD

**Issue by HarryAdney** [brapifra/vscode-phpserver#52]
When I run the server on index.php, the browser attempts to open dex.php; the first two characters "in" are missing.

Tried with several pages with the same result
![dex-php](https://user-images.githubusercontent.com/8182847/52717919-21cc0a80-2f9a-11e9-81d1-f96580aaa8c7.png)

**Comment by HarryAdney** [comment]
![dex-php](https://user-images.githubusercontent.com/8182847/52718653-e3374f80-2f9b-11e9-96ec-27fda032b817.png)

**Comment by HarryAdney** [comment]
Any update?

**Comment by HarryAdney** [comment]
Never mind - fixed it.

**Comment by suttonmay** [comment]
Can you share what you did to fix this? I'm getting the same thing currently.

**Comment by HarryAdney** [comment]
Actually, I ended up reinstalling VSCode. No problem since. It's a weird one though.
