### ISSUE TITLE
root-path ≠ current work directory on Multi-root Workspaces situation

### ISSUE THREAD

**Issue by mygh021** [brapifra/vscode-phpserver#55]
On the Occasion : Multi-root Workspaces in Visual Studio Code ,It may not working correctly.Because vscode.workspace.rootPath corresponds to the first entry of workspaceFolders

Core API:
workspace.workspaceFolders	access to all WorkspaceFolder (can be undefined when no workspace is opened!)
workspace.onDidChangeWorkspaceFolders	be notified when WorkspaceFolder are added or removed
workspace.getWorkspaceFolder(uri)

So,To make it work, we can use workspace.getWorkspaceFolder(uri) to get the root-path instead.

**Comment by brapifra** [comment]
Hi,

Yes, I'm aware that it doesn't work with multiple workspaces.
I will try to fix it in the near future. Thanks.

**Comment by brapifra** [comment]
Fixed in v3.0.1
Related to https://github.com/brapifra/vscode-phpserver/issues/73
