### ISSUE TITLE
Error when starting the server

### ISSUE THREAD

**Issue by arthur-rl** [brapifra/vscode-phpserver#57]
This is the error im getting:

Server error: Error: spawn php ENOENT at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19) at onErrorNT (internal/child_process.js:406:16) at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by CHIGonzales** [comment]
Me too having this error

**Comment by CHIGonzales** [comment]
RIght, i fixed the problem by installing php silly me. i'm using Ubuntu right now and yeah it works.

**Comment by Jackiin** [comment]
Is there any solution for Windows?

**Comment by rvxy** [comment]
> Is there any solution for Windows?

https://www.sitepoint.com/how-to-install-php-on-windows/

**Comment by rvxy** [comment]
> Is there any solution for Windows?
I'm using PHP 7.3 on W10 and it works fine for me.

**Comment by brapifra** [comment]
Hi! Apologies for the delayed response.

When are you getting than error? Also, are you using Windows?

**Comment by Sormik** [comment]
🤦‍♂️ Fixed it with this one:
https://www.sitepoint.com/how-to-install-php-on-windows/
