### ISSUE TITLE
Normal version of Chrome being selected instead of Chrome Dev despite focus

### ISSUE THREAD

**Issue by Leon9021** [brapifra/vscode-phpserver#58]
Hello,

To put this into context, basically, I would very much like to be able to tie the server, to starting only in Chrome Dev, as I have many other Chrome profiles open, in which I really don't want the server to start it.

In the past I solved this issue by focusing Chrome Dev so that the server would open inside of it upon reloading... however, for some reason currently, the server only opens in the normal version of Chrome, rather than the Dev, despite focusing it before reloading the server... (probably a Chrome Dev/Chrome update that ruined this somehow)

So yeah, could there perhaps be an implementation of an option, that ties the server to a specific Chrome version/browser directory?

Another live server extension, handles this beautifully where one can simply apply:

"liveServer.settings.AdvanceCustomBrowserCmdLine": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe --profile-directory=Profile 8",

Inside of the settings.json of VSCode

Thereby permanently tying a live server to an X browser/version/directory of it, instead of being stuck to something undesirable and largely inconvenient, as per one's custom setup

Kind regards.
Leo

**Comment by kungpaogao** [comment]
Did you find a solution to this? I'm using Firefox Developer Edition.

I might open a PR to make this more flexible.
```typescript
case "firefox":
        if (platform() === 'linux') {
          browser = `${browser} http://${ip}:${port}/${fileName}`;
        } else if (platform() === "win32") {
          browser = `start ${browser} http://${ip}:${port}/${fileName}`;
        } else if (platform() === 'darwin') {
          // could be abstracted
          browser = `open -a "Firefox" http://${ip}:${port}/${fileName}`;
        } else {
          browser = '';
        }
        break;
```
