### ISSUE TITLE
Add support for Edge on MAC

### ISSUE THREAD

**Issue by gragra33** [brapifra/vscode-phpserver#59]
Can the following be added to `Server.ts` or a version of it?
```js
if (platform() === 'win32') {
  browser = `start microsoft-edge:http://${ip}:${port}/${fileName}`;
} else if (platform() === 'darwin') {
  browser = `open -a "Microsoft Edge Canary" http://${ip}:${port}/${fileName}`;
} else if (platform() === 'darwin') {
  browser = `open -a "Microsoft Edge" http://${ip}:${port}/${fileName}`;
} else {
  browser = '';
}
```
I would rather not fork and modify for my own use. Thanks

**Comment by brapifra** [comment]
Hello!

Yeah, I guess I could add it if you're still interested in that feature.

**Comment by emartinez06** [comment]
I think this is useful. I'm interested in this feature.

**Comment by brapifra** [comment]
Hey @emartinez06 @gragra33 
Since v3.0.1, the extension opens the default browser by default. You can also specify any custom one with the `phpserver.browser` setting.
Just upgrade the extension to the latest release (v3.0.1) :slightly_smiling_face:
