### ISSUE TITLE
Running on windows

### ISSUE THREAD

**Issue by JorgeGRC** [brapifra/vscode-phpserver#6]
I'm trying to run this on windows but can't get the server to work. 

I'm currently learning php and have a small web project in my hard drive. Opened VSCode to work on that project folder, selected one of the project's .php file to edit and used this extension to "start php server". 
The message which tells you that the server has started up successfully and project is being served appeared. So far so good, then went into chrome to access this php file and all I see is the content, it's not getting run at all...

Probably I'm missing something really stupid but I can't get what it is :(. It would be good to find a small example on the docs or something like that to get started.

PHP version is 7.0, my OS is Windows 10, and I configured the settings.json to use Chrome as my web-browser with this VS extension. Any help appreciated.

Regards

**Comment by brapifra** [comment]
What do you mean with not getting run at all? Are you saying that you see the content of the php file when you go into chrome?

**Comment by JorgeGRC** [comment]
> Are you saying that you see the content of the php file when you go into chrome?
Yes, exactly that, as the server wouldn't run the php file and I just see all the content on chrome

> Have you apache or another server installed?
I do have a XAMPP instance on my machine but it's not working on the same directory that I'm trying to run your php-server. Also, I installed xampp after I saw I couldn't get the php server to run and I was able to see the php file content, so that's why I downloaded xampp and began using it, but it's time wasting to copy over and over again my php files into the XAMPP directory from my working copy directory :(

**Comment by brapifra** [comment]
Which URL are you entering?
PS: Are you Spanish? Because in that case we are wasting time writing in English haha

**Comment by JorgeGRC** [comment]
Soy español sí :) estaba utilizando el inglés por si alguien más viene dentro de un tiempo y lo encuentra útil.. Básicamente la URL que aparece, y me acabo de dar cuenta, es con el prefijo file:// y seguramente por eso estoy viendo el contenido del fichero .php jaja, el caso es que al intentar lanzar el servidor php habiendo especificado en las opciones "chrome", no me lanza automáticamente una ventana del navegador, sino que me sale el mensaje de que ya está sirviendo el proyecto. Gracias por tu paciencia

**Comment by brapifra** [comment]
Me olía que irían por ahí los tiros! jaja
Pues sí, 3º de Teleco por Telemática (Plan Bolonia), y cuando tengo algún huequillo trasteo un poco jeje
Miraré eso que dices de que no se abre chrome automáticamente, desde Linux, que es lo que uso, va.
Un saludo! ;)

-----ENGLISH-----
Summing up, problem fixed, Jorge was entering a wrong URL (file:\\ instead of localhost). Nevertheless, I'll check why chrome doesn't open automatically in Windows.
