### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by iemadk** [brapifra/vscode-phpserver#61]
Some of the features require https, it would be great to have an option for starting https server instead of http.
you can either specify default location or ask the user for the configuration inside the VSCode settings.

**Comment by josematheus10** [comment]
I need this https support :-/

**Comment by brapifra** [comment]
This extension uses php's built-in server under the hood, which unfortunately doesn't have HTTPS support.
Given the limited scope of the extension, I don't think it's worth it to add the option to encrypt traffic with SSL/TLS. You could easily setup an HTTPS proxy server with nginx pointing to the development server created by the extension.
I hope that helped! :slightly_smiling_face:
