### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by Lukzee** [brapifra/vscode-phpserver#66]
Issue Type: <b>Performance Issue</b>

It is hard to setting most of the extensions

Extension version: 2.4.6
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 6.1.7601

**Comment by brapifra** [comment]
This was most likely not caused by this extension. In any case, feel free to re-open if you still have the issue while using `vscode-phpserver`
