### ISSUE TITLE
Server error: Error: spawn php ENOENT

### ISSUE THREAD

**Issue by thabisoram** [brapifra/vscode-phpserver#67]
When I launch the PHP Server from VSCode this is what I see...

Server error: Error: spawn php ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)

![PHPSERVERISSUE](https://user-images.githubusercontent.com/58775188/72204139-5af84d80-347d-11ea-8a26-fa1dbf45d5e1.JPG)

**Comment by thabisoram** [comment]
its most probably my configurations

**Comment by LeoDev0** [comment]
I solved this problem by manually adding the php executable file path to the line "phpserver.phpPath" on vscode settings json file. Find where's this php executable on your machine and add the path at this line. In my case, (debian linux machine running Xampp), adding this line ("phpserver.phpPath": "/opt/lampp/bin/php) on the vscode settings file worked.

![php-server](https://user-images.githubusercontent.com/60330828/74390637-a6857a80-4de0-11ea-889a-715a6e645515.png)

**Comment by brapifra** [comment]
Yup, this is usually the reason why people get this error. In the latest release (v3.0.1), I've improved the error messaging so it's easier to debug :slightly_smiling_face: 
Thank you @LeoDev0 for your comment :wink:
