### ISSUE TITLE
Cannot open localhost:3000 in chromium | Endeavour OS (linux)

### ISSUE THREAD

**Issue by morocinza** [brapifra/vscode-phpserver#68]
This is my settings.json:

`"phpserver.phpPath": "/opt/lampp/bin/php",
"php.validate.executablePath": "/opt/lampp/bin/php",
"phpserver.browser": "chromium",
"phpserver.port": 3000`

Open up a new blank chromium page

**Comment by prepre73** [comment]
Hey,

I'm  having the same issue on linux using elementry os, though I believe you should have 
```
"phpserver.browser": "chromium-browser", 
```

> **Anyone know what the local serve url should be?** 

Thanks

**Comment by brapifra** [comment]
Hey @morocinza
This wasn't supported in previous versions, but @prepre73 's recommendation is now valid in the latest release (v3.0.1). Just make sure you're using that one :wink:
