### ISSUE TITLE
Windows fresh installation - error starting server

### ISSUE THREAD

**Issue by BananaAcid** [brapifra/vscode-phpserver#70]
```
Server error: Error: spawn php ENOENT at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19) at onErrorNT (internal/child_process.js:456:16) at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

only VSCODE is installed as these school instances for students are only configured with vscode and some plugins. 

disabling "automatically open file in browser" does not fix this.

**Comment by NathanKassab** [comment]
same issue for me, i don't know why the live server plugin doesn't have php support so now im forced to use this. the issue is that it is broken

**Comment by snpdev** [comment]
Ensure that:

1. You have php installed
2. PHP Path is set as in the image below. Of course, your path will probably be different and the example below is for Windows.

![image](https://user-images.githubusercontent.com/1825479/88337259-69fd6980-cd04-11ea-8e04-da526dc816f2.png)

**Comment by brapifra** [comment]
Yup, @snpdev is right.
In any case, I'd recommend to upgrade the extension to the latest release (v3.0.1). It contains improvements on error logging that can help you debug the issue.
