### ISSUE TITLE
"PHP installed." what? how?

### ISSUE THREAD

**Issue by BananaAcid** [brapifra/vscode-phpserver#71]
What is needed, to have this plugin recognize the C:\PHP installation?

A little more info would be great.

... AND: Why is it not using / falling back to the settings.json `php.validate.executablePath` path ??

VSCode wants it to be configured for PHP-Validation anyways like the following (working):
```
"php.validate.executablePath": "C:/PHP/php.exe",
```

**Comment by snpdev** [comment]
Won't work on Windows with unix style forward slashes. Try `C:\PHP\php.exe` instead.

**Comment by BananaAcid** [comment]
Your answer is not related to my question. And the php.validate works fine with this style, as all nodejs code does for me.

**Comment by brapifra** [comment]
Hey @BananaAcid 
`php.validate` is not part of the extension settings. I assume that it's a setting from another extension?
As long as the path to the php executable is correct, it should work. Could you perhaps try again in latest release (v3.0.1)?
I'm going to close the issue for now, but we can re-open it if needed.

**Comment by BananaAcid** [comment]
True, it is part of VSCode's native settings. https://code.visualstudio.com/docs/languages/php
