### ISSUE TITLE
Server starts and closes (windows)

### ISSUE THREAD

**Issue by BananaAcid** [brapifra/vscode-phpserver#72]
1. Fresh Windows 10 Sandbox.
2. Chrome installed
3. PHP extracted to C:\PHP
4. VSCode installed
5. plugin installed
6. user settings.json
```json
{
    "php.validate.executablePath": "C:/PHP/php.exe",
    "phpserver.phpPath": "C:\\PHP\\php.exe",
}
```
7. php server start 

RESULT:
-> shows started and stopped right after each other. no error output to be found.

**Comment by brapifra** [comment]
Hey @BananaAcid 
Could you update the extension to v3.0.1 and see if the issue is still happening?
I'm going to close the ticket for now. We can re-open it if needed slightly_smiling_face
