### ISSUE TITLE
Can't stop server on Windows

### ISSUE THREAD

**Issue by profiluefter** [brapifra/vscode-phpserver#74]
Hi, I have the same issue as several other closed issues: After starting a php instance using this plugin, I can only stop it using the Task Manager. I'm using Windows 10 and don't think that another plugin is interfering.

**Comment by brapifra** [comment]
Hey @profiluefter
Could you try to update the extension to v3.0.1 and see if the issue is still happening?
I'm going to close the ticket for now. We can re-open it if needed :slightly_smiling_face:
