### ISSUE TITLE
command 'extension.phpServer.serveProject' not found

### ISSUE THREAD

**Issue by tafseen-rahman** [brapifra/vscode-phpserver#79]
After few second vs code notification shows that **command  'extension.phpServer.serveProject' not found**. How can I solve this problem?

**Comment by brapifra** [comment]
Hey @tafseen-rahman 
Could you try to update the extension to v3.0.1 and see if the issue is still happening?
I'm going to close the ticket for now. We can re-open it if needed :slightly_smiling_face:
