### ISSUE TITLE
Session are Not working

### ISSUE THREAD

**Issue by goelpulkit97** [brapifra/vscode-phpserver#86]
I tried using sessions but they are not working so can you please help me with that?

**Comment by roberi** [comment]
I would like a solution for session also.

**Comment by TheArchitect4855** [comment]
I had the same issue. Turns out (this is something I forgot), you have to call `session_start()` on *every* page that uses session variables. This is a normal PHP thing that I didn't know about (I'm getting reacquainted with PHP after not using it for a very long time). 

Hopefully that helps.

**Comment by goelpulkit97** [comment]
Thanks for replying. Actually in older version of this plugin the sessions were not supported. Thanks for trying to resolve the issue. Really appreciate your comment.
